/* ── Subjects ──────────────────────────────────────────────────── */
const SUBJECTS = [
  { id: 'as_physics',   name: 'AS Physics',       level: 'AS',    syllabus: '9702', color: '#3b82f6', icon: '⚛' },
  { id: 'as_maths',     name: 'AS Mathematics',   level: 'AS',    syllabus: '9709', color: '#a855f7', icon: '∑' },
  { id: 'ig_biology',   name: 'IGCSE Biology',    level: 'IGCSE', syllabus: '0610', color: '#22c55e', icon: '🧬' },
  { id: 'ig_chemistry', name: 'IGCSE Chemistry',  level: 'IGCSE', syllabus: '0620', color: '#f59e0b', icon: '⚗' },
  { id: 'ig_economics', name: 'IGCSE Economics',  level: 'IGCSE', syllabus: '0455', color: '#06b6d4', icon: '📊' },
  { id: 'ig_english',   name: 'IGCSE English Lit',level: 'IGCSE', syllabus: '0475', color: '#ec4899', icon: '📖' },
];
const SUBJECT_MAP = Object.fromEntries(SUBJECTS.map(s => [s.id, s]));

/* ── Questions ─────────────────────────────────────────────────── */
const QUESTIONS = [
  // ─── AS PHYSICS ────────────────────────────────────────────────
  {
    id: 'phy_001', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Physical Quantities and Units', subtopic: 'SI base units',
    syllabusRef: '1.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['units', 'dimensional analysis'],
    tags: ['SI units', 'base units', 'pressure'], examFrequency: 'high',
    prompt: 'Which expression has the same SI base units as pressure?',
    options: [
      'force / (length × speed)',
      'force / (length × time)',
      'mass / (length × time²)',
      'mass × time² / length',
    ],
    correctAnswer: 2,
    explanation: 'Pressure = Force / Area = kg m⁻¹ s⁻². Option C: mass/(length×time²) = kg/(m·s²) = kg m⁻¹ s⁻² ✓',
    commonMistakes: ['Confusing force units with pressure units', 'Forgetting area contributes m²'],
    teachingSteps: [
      'Write pressure = force / area',
      'Expand force = kg·m·s⁻² and area = m²',
      'Simplify to get kg·m⁻¹·s⁻²',
      'Check each option by expanding units',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'phy_002', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Kinematics', subtopic: 'SUVAT equations',
    syllabusRef: '2.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['kinematics', 'equation selection'],
    tags: ['SUVAT', 'free fall'], examFrequency: 'high',
    prompt: 'A ball is dropped from rest and falls for 2.0 s. How far does it fall? (g = 9.81 m s⁻²)',
    options: ['9.81 m', '4.91 m', '19.62 m', '39.24 m'],
    correctAnswer: 2,
    explanation: 'Using s = ut + ½gt² with u = 0: s = ½ × 9.81 × 2² = 19.62 m.',
    commonMistakes: ['Using s = gt instead of ½gt²', 'Forgetting u = 0'],
    teachingSteps: [
      'Identify: u = 0, a = g, t = 2.0 s',
      'Select equation: s = ut + ½at²',
      'Substitute: s = 0 + ½(9.81)(4.0)',
      'Calculate: s = 19.62 m',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'phy_003', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Dynamics', subtopic: "Newton's second law",
    syllabusRef: '3.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['force', 'acceleration'],
    tags: ['F=ma', 'dynamics'], examFrequency: 'high',
    prompt: 'A resultant force of 24 N acts on a 6.0 kg mass. What is the acceleration?',
    options: ['144 m s⁻²', '4.0 m s⁻²', '0.25 m s⁻²', '30 m s⁻²'],
    correctAnswer: 1,
    explanation: 'F = ma, so a = F/m = 24/6.0 = 4.0 m s⁻².',
    commonMistakes: ['Multiplying force × mass', 'Using weight instead of mass'],
    teachingSteps: ['Recall F = ma', 'Rearrange: a = F/m', 'Substitute: a = 24/6.0', 'a = 4.0 m s⁻²'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'phy_004', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Work, Energy and Power', subtopic: 'Kinetic energy',
    syllabusRef: '5.2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'calculation', marks: 2,
    skillsTested: ['energy', 'calculation'],
    tags: ['KE', 'conservation'], examFrequency: 'high',
    prompt: 'A 1200 kg car travels at 25 m s⁻¹. Calculate its kinetic energy.',
    options: null, correctAnswer: '375000',
    explanation: 'KE = ½mv² = ½ × 1200 × 25² = 375 000 J = 375 kJ.',
    commonMistakes: ['Forgetting to square velocity', 'Forgetting the ½'],
    teachingSteps: ['Write KE = ½mv²', 'Substitute: KE = ½ × 1200 × 625', 'Calculate: KE = 375 000 J'],
    aiMarkable: true, markScheme: ['½mv² stated or used [1]', '375 000 J or 375 kJ [1]'],
  },
  {
    id: 'phy_005', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Waves', subtopic: 'Wave equation',
    syllabusRef: '7.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['waves'],
    tags: ['wave speed', 'frequency'], examFrequency: 'high',
    prompt: 'A wave has frequency 250 Hz and wavelength 1.36 m. What is its speed?',
    options: ['184 m s⁻¹', '340 m s⁻¹', '250 m s⁻¹', '0.00544 m s⁻¹'],
    correctAnswer: 1,
    explanation: 'v = fλ = 250 × 1.36 = 340 m s⁻¹.',
    commonMistakes: ['Dividing instead of multiplying', 'Confusing period and frequency'],
    teachingSteps: ['Recall v = fλ', 'Substitute values', 'v = 250 × 1.36 = 340 m s⁻¹'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'phy_006', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Electricity', subtopic: 'Resistance',
    syllabusRef: '9.3', difficulty: 'medium', difficultyScore: 2,
    questionType: 'short-answer', marks: 3,
    skillsTested: ['electricity', 'resistivity'],
    tags: ['resistance', 'wire'], examFrequency: 'medium',
    prompt: 'A copper wire has length 2.0 m, cross-sectional area 1.0 × 10⁻⁶ m² and resistivity 1.7 × 10⁻⁸ Ω m. Calculate its resistance.',
    options: null, correctAnswer: '0.034',
    explanation: 'R = ρL/A = (1.7×10⁻⁸ × 2.0) / (1.0×10⁻⁶) = 0.034 Ω.',
    commonMistakes: ['Rearranging ρ = RA/L incorrectly', 'Powers of 10 errors'],
    teachingSteps: [
      'Write R = ρL/A',
      'Substitute: R = (1.7×10⁻⁸ × 2.0) / (1.0×10⁻⁶)',
      'Calculate numerator: 3.4×10⁻⁸',
      'Divide: 3.4×10⁻⁸ / 10⁻⁶ = 0.034 Ω',
    ],
    aiMarkable: true, markScheme: ['R = ρL/A used [1]', 'Correct substitution [1]', 'R = 0.034 Ω [1]'],
  },
  {
    id: 'phy_007', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 1', topic: 'Superposition', subtopic: 'Diffraction grating',
    syllabusRef: '8.4', difficulty: 'hard', difficultyScore: 3,
    questionType: 'mcq', marks: 1,
    skillsTested: ['superposition', 'calculation'],
    tags: ['diffraction grating', 'wavelength'], examFrequency: 'medium',
    prompt: 'A diffraction grating has 500 lines per mm. Light of wavelength 600 nm is used. What is the maximum observable order of diffraction?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    explanation: 'd = 1/(500×10³) = 2×10⁻⁶ m. n_max = d/λ = 2×10⁻⁶/6×10⁻⁷ = 3.33, so n_max = 3.',
    commonMistakes: ['Not finding d from lines/mm', 'Forgetting sinθ ≤ 1'],
    teachingSteps: [
      'Calculate d = 1/(500 000) m = 2×10⁻⁶ m',
      'Use d sinθ = nλ with sinθ_max = 1',
      'n_max = d/λ = 2×10⁻⁶ / 6×10⁻⁷ = 3.33',
      'Round down: n_max = 3',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'phy_008', subject: 'as_physics', level: 'AS', syllabus: '9702',
    paper: 'Paper 2', topic: 'Particle Physics', subtopic: 'Quarks',
    syllabusRef: '11.2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['particles'],
    tags: ['quarks', 'proton'], examFrequency: 'medium',
    prompt: 'A proton consists of which quarks?',
    options: ['uud', 'udd', 'uuu', 'uds'],
    correctAnswer: 0,
    explanation: 'Proton = up + up + down (uud). Charge: +⅔ +⅔ -⅓ = +1.',
    commonMistakes: ['Mixing up proton and neutron compositions', 'Getting quark charges wrong'],
    teachingSteps: [
      'Proton charge = +1e',
      'Up quark = +⅔e, down quark = -⅓e',
      'Check: uud = +⅔+⅔-⅓ = +1 ✓',
      'Neutron would be udd = 0',
    ],
    aiMarkable: false, markScheme: null,
  },

  // ─── AS MATHEMATICS ────────────────────────────────────────────
  {
    id: 'math_001', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Quadratics', subtopic: 'Completing the square',
    syllabusRef: '1.2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'calculation', marks: 3,
    skillsTested: ['algebra', 'manipulation'],
    tags: ['quadratic', 'completing square'], examFrequency: 'high',
    prompt: 'Express x² + 6x + 2 in the form (x + a)² + b. State the values of a and b.',
    options: null, correctAnswer: 'a=3, b=-7',
    explanation: 'x² + 6x + 2 = (x + 3)² - 9 + 2 = (x + 3)² - 7. So a = 3, b = -7.',
    commonMistakes: ['Sign error: writing +9 instead of -9', 'Forgetting to add the constant term'],
    teachingSteps: [
      'Halve the coefficient of x: 6/2 = 3',
      'Write (x + 3)² = x² + 6x + 9',
      'Adjust: x² + 6x + 2 = (x+3)² - 9 + 2',
      'Simplify: (x+3)² - 7',
    ],
    aiMarkable: true, markScheme: ['(x + 3)² seen [1]', '−9 + 2 attempted [1]', 'a = 3, b = −7 [1]'],
  },
  {
    id: 'math_002', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Coordinate Geometry', subtopic: 'Straight lines',
    syllabusRef: '2.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['gradient', 'coordinates'],
    tags: ['gradient', 'midpoint'], examFrequency: 'high',
    prompt: 'What is the gradient of the line joining (1, 3) and (5, 11)?',
    options: ['2', '4', '½', '8'],
    correctAnswer: 0,
    explanation: 'm = (y₂-y₁)/(x₂-x₁) = (11-3)/(5-1) = 8/4 = 2.',
    commonMistakes: ['Subtracting coordinates in wrong order', 'Dividing Δx by Δy'],
    teachingSteps: ['Use m = (y₂-y₁)/(x₂-x₁)', 'Substitute: (11-3)/(5-1)', 'Calculate: 8/4 = 2'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'math_003', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Functions', subtopic: 'Domain and range',
    syllabusRef: '3.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'short-answer', marks: 2,
    skillsTested: ['functions'],
    tags: ['range', 'quadratic'], examFrequency: 'medium',
    prompt: 'f(x) = x² − 4x + 7 for x ∈ ℝ. Find the range of f.',
    options: null, correctAnswer: 'f(x) ≥ 3',
    explanation: 'Complete the square: f(x) = (x-2)² + 3. Minimum value is 3. Range: f(x) ≥ 3.',
    commonMistakes: ['Not completing the square', 'Writing range as x ≥ 3 instead of f(x) ≥ 3'],
    teachingSteps: [
      'Complete the square: (x-2)² + 3',
      'Minimum of (x-2)² is 0, when x = 2',
      'Minimum of f(x) is 0 + 3 = 3',
      'Range: f(x) ≥ 3',
    ],
    aiMarkable: true, markScheme: ['Completed square form [1]', 'Range: f(x) ≥ 3 [1]'],
  },
  {
    id: 'math_004', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Differentiation', subtopic: 'Basic rules',
    syllabusRef: '7.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'calculation', marks: 2,
    skillsTested: ['calculus'],
    tags: ['differentiation', 'power rule'], examFrequency: 'high',
    prompt: 'Differentiate y = 3x⁴ − 2x² + 5x.',
    options: null, correctAnswer: '12x³ − 4x + 5',
    explanation: 'dy/dx = 12x³ − 4x + 5. Apply the power rule to each term.',
    commonMistakes: ['Forgetting to reduce the power by 1', 'Not differentiating the constant coefficient'],
    teachingSteps: ['Apply power rule: d/dx(xⁿ) = nxⁿ⁻¹', '3x⁴ → 12x³', '−2x² → −4x', '5x → 5'],
    aiMarkable: true, markScheme: ['At least two terms correct [1]', 'All three terms correct [1]'],
  },
  {
    id: 'math_005', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Integration', subtopic: 'Definite integrals',
    syllabusRef: '8.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'calculation', marks: 3,
    skillsTested: ['calculus', 'integration'],
    tags: ['definite integral'], examFrequency: 'high',
    prompt: 'Evaluate ∫₁³ (2x + 1) dx.',
    options: null, correctAnswer: '10',
    explanation: '∫(2x+1)dx = x² + x + C. [x² + x]₁³ = (9+3) − (1+1) = 12 − 2 = 10.',
    commonMistakes: ['Forgetting to evaluate at both limits', 'Integration errors with constants'],
    teachingSteps: ['Integrate: x² + x', 'Upper limit: 3² + 3 = 12', 'Lower limit: 1² + 1 = 2', 'Subtract: 12 − 2 = 10'],
    aiMarkable: true, markScheme: ['Correct integral x² + x [1]', 'Substitution of limits [1]', 'Answer = 10 [1]'],
  },
  {
    id: 'math_006', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Trigonometry', subtopic: 'Identities',
    syllabusRef: '5.1', difficulty: 'hard', difficultyScore: 3,
    questionType: 'short-answer', marks: 4,
    skillsTested: ['trigonometry', 'proof'],
    tags: ['trig identity', 'proof'], examFrequency: 'medium',
    prompt: 'Solve 2sin²θ + sinθ − 1 = 0 for 0° ≤ θ ≤ 360°.',
    options: null, correctAnswer: '30, 150, 270',
    explanation: 'Let s = sinθ. 2s² + s − 1 = 0 → (2s−1)(s+1) = 0. sinθ = ½ → θ = 30°, 150°. sinθ = −1 → θ = 270°.',
    commonMistakes: ['Missing solutions in different quadrants', 'Factoring incorrectly'],
    teachingSteps: [
      'Substitute s = sinθ',
      'Factor: (2s−1)(s+1) = 0',
      's = ½ or s = −1',
      'Find all θ in range: 30°, 150°, 270°',
    ],
    aiMarkable: true, markScheme: ['Correct factorisation [1]', 'sinθ = ½ and sinθ = −1 [1]', '30° and 150° [1]', '270° [1]'],
  },
  {
    id: 'math_007', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 1', topic: 'Series', subtopic: 'Arithmetic progression',
    syllabusRef: '4.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['sequences'],
    tags: ['AP', 'nth term'], examFrequency: 'high',
    prompt: 'An arithmetic sequence has first term 5 and common difference 3. What is the 20th term?',
    options: ['60', '62', '65', '57'],
    correctAnswer: 1,
    explanation: 'aₙ = a + (n−1)d = 5 + 19(3) = 5 + 57 = 62.',
    commonMistakes: ['Using n instead of n−1', 'Adding instead of multiplying d'],
    teachingSteps: ['Use aₙ = a + (n−1)d', 'a₂₀ = 5 + (20−1)(3)', '= 5 + 57 = 62'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'math_008', subject: 'as_maths', level: 'AS', syllabus: '9709',
    paper: 'Paper 6', topic: 'Statistics', subtopic: 'Probability',
    syllabusRef: 'S1.5', difficulty: 'medium', difficultyScore: 2,
    questionType: 'calculation', marks: 2,
    skillsTested: ['probability'],
    tags: ['independent events'], examFrequency: 'high',
    prompt: 'Two fair dice are thrown. What is the probability that the sum is 7?',
    options: null, correctAnswer: '1/6',
    explanation: 'Combinations summing to 7: (1,6)(2,5)(3,4)(4,3)(5,2)(6,1) = 6 out of 36. P = 6/36 = 1/6.',
    commonMistakes: ['Counting combinations wrong', 'Using 12 instead of 36 total outcomes'],
    teachingSteps: ['Total outcomes = 6 × 6 = 36', 'List pairs summing to 7', 'Count: 6 favourable outcomes', 'P = 6/36 = 1/6'],
    aiMarkable: true, markScheme: ['6 favourable or 36 total [1]', '1/6 or equivalent [1]'],
  },

  // ─── IGCSE BIOLOGY ─────────────────────────────────────────────
  {
    id: 'bio_001', subject: 'ig_biology', level: 'IGCSE', syllabus: '0610',
    paper: 'Paper 2', topic: 'Cell Structure', subtopic: 'Plant vs animal cells',
    syllabusRef: '2.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['recall'],
    tags: ['cells', 'organelles'], examFrequency: 'high',
    prompt: 'Which structure is found in plant cells but NOT in animal cells?',
    options: ['Nucleus', 'Cell wall', 'Mitochondria', 'Cell membrane'],
    correctAnswer: 1,
    explanation: 'Cell walls made of cellulose are unique to plant cells. Both plant and animal cells have nuclei, mitochondria, and cell membranes.',
    commonMistakes: ['Confusing cell wall with cell membrane', 'Thinking mitochondria are plant-only'],
    teachingSteps: [
      'Plant cells have: cell wall, chloroplasts, large vacuole',
      'Animal cells lack these three',
      'Both have: nucleus, membrane, mitochondria, ribosomes',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'bio_002', subject: 'ig_biology', level: 'IGCSE', syllabus: '0610',
    paper: 'Paper 2', topic: 'Enzymes', subtopic: 'Lock and key model',
    syllabusRef: '5.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'short-answer', marks: 3,
    skillsTested: ['explanation', 'application'],
    tags: ['enzymes', 'denaturation'], examFrequency: 'high',
    prompt: 'Explain why enzymes stop working at high temperatures.',
    options: null, correctAnswer: null,
    explanation: "At high temperatures, the kinetic energy causes bonds holding the enzyme's tertiary structure to break. The active site changes shape (denatures) and the substrate can no longer fit, so the reaction cannot be catalysed.",
    commonMistakes: ["Saying the enzyme 'dies'", 'Confusing denaturation with reversible effects of low temperature'],
    teachingSteps: [
      'Enzymes have a specific 3D shape',
      'High temperature breaks bonds in the enzyme',
      'Active site changes shape = denaturation',
      'Substrate no longer fits = no reaction',
    ],
    aiMarkable: true, markScheme: ['Bonds in enzyme break / tertiary structure disrupted [1]', 'Active site changes shape [1]', 'Substrate no longer fits / complementary [1]'],
  },
  {
    id: 'bio_003', subject: 'ig_biology', level: 'IGCSE', syllabus: '0610',
    paper: 'Paper 4', topic: 'Photosynthesis', subtopic: 'Limiting factors',
    syllabusRef: '6.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['application'],
    tags: ['photosynthesis', 'graphs'], examFrequency: 'high',
    prompt: 'A plant is in bright light with plenty of CO₂. Which factor is most likely to be limiting photosynthesis?',
    options: ['Light intensity', 'Carbon dioxide concentration', 'Temperature', 'Water availability'],
    correctAnswer: 2,
    explanation: 'With bright light and plenty of CO₂, temperature becomes the limiting factor as it affects enzyme activity in the Calvin cycle.',
    commonMistakes: ["Choosing light when it's already bright", 'Ignoring enzyme dependency on temperature'],
    teachingSteps: [
      'Identify which factors are already abundant',
      'Light = bright ✓, CO₂ = plenty ✓',
      'Temperature controls enzyme rate',
      'Temperature is the limiting factor',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'bio_004', subject: 'ig_biology', level: 'IGCSE', syllabus: '0610',
    paper: 'Paper 2', topic: 'Respiration', subtopic: 'Aerobic vs anaerobic',
    syllabusRef: '7.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['recall', 'comparison'],
    tags: ['respiration', 'ATP'], examFrequency: 'high',
    prompt: 'Which is a product of anaerobic respiration in yeast?',
    options: ['Oxygen', 'Carbon dioxide and ethanol', 'Lactic acid only', 'Water and glucose'],
    correctAnswer: 1,
    explanation: 'In yeast, anaerobic respiration produces ethanol and carbon dioxide. In animals, it produces lactic acid.',
    commonMistakes: ['Confusing yeast and animal anaerobic products', 'Including oxygen as a product'],
    teachingSteps: [
      'Anaerobic = without oxygen',
      'In yeast: glucose → ethanol + CO₂',
      'In animals: glucose → lactic acid',
      "Don't mix these up!",
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'bio_005', subject: 'ig_biology', level: 'IGCSE', syllabus: '0610',
    paper: 'Paper 4', topic: 'Genetics', subtopic: 'Monohybrid crosses',
    syllabusRef: '16.1', difficulty: 'hard', difficultyScore: 3,
    questionType: 'short-answer', marks: 4,
    skillsTested: ['genetics', 'Punnett square'],
    tags: ['inheritance', 'dominant', 'recessive'], examFrequency: 'high',
    prompt: 'In pea plants, tall (T) is dominant over short (t). Two heterozygous plants are crossed. What ratio of tall to short offspring is expected?',
    options: null, correctAnswer: '3:1',
    explanation: 'Tt × Tt → TT, Tt, Tt, tt. Phenotype ratio: 3 tall : 1 short.',
    commonMistakes: ['Writing genotype ratio instead of phenotype ratio', 'Forgetting heterozygous means Tt'],
    teachingSteps: [
      'Parents: Tt × Tt',
      'Draw Punnett square',
      'Offspring: TT, Tt, Tt, tt',
      'Phenotypes: 3 tall (TT+Tt+Tt) : 1 short (tt)',
    ],
    aiMarkable: true, markScheme: ['Correct parental genotypes [1]', 'Punnett square correct [1]', 'All four offspring genotypes [1]', '3:1 ratio stated [1]'],
  },
  {
    id: 'bio_006', subject: 'ig_biology', level: 'IGCSE', syllabus: '0610',
    paper: 'Paper 4', topic: 'Ecology', subtopic: 'Food chains',
    syllabusRef: '19.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['ecology'],
    tags: ['food chain', 'energy transfer'], examFrequency: 'medium',
    prompt: 'In a food chain, what happens to the amount of energy at each trophic level?',
    options: ['It increases', 'It stays the same', 'It decreases', 'It doubles'],
    correctAnswer: 2,
    explanation: 'Energy decreases at each trophic level because organisms use energy for life processes (respiration) and some is lost as heat.',
    commonMistakes: ['Thinking energy increases up the chain', 'Forgetting energy loss through respiration'],
    teachingSteps: [
      'Energy enters via producers (photosynthesis)',
      'At each level, ~90% is lost',
      'Lost to: respiration, heat, excretion',
      'Only ~10% passes to next level',
    ],
    aiMarkable: false, markScheme: null,
  },

  // ─── IGCSE CHEMISTRY ───────────────────────────────────────────
  {
    id: 'chem_001', subject: 'ig_chemistry', level: 'IGCSE', syllabus: '0620',
    paper: 'Paper 2', topic: 'Atomic Structure', subtopic: 'Subatomic particles',
    syllabusRef: '3.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['recall'],
    tags: ['atoms', 'protons', 'electrons'], examFrequency: 'high',
    prompt: 'An atom of sodium-23 has 11 protons. How many neutrons does it have?',
    options: ['11', '12', '23', '34'],
    correctAnswer: 1,
    explanation: 'Neutrons = mass number − proton number = 23 − 11 = 12.',
    commonMistakes: ['Adding instead of subtracting', 'Confusing mass number with atomic number'],
    teachingSteps: ['Mass number = protons + neutrons', '23 = 11 + neutrons', 'Neutrons = 23 − 11 = 12'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'chem_002', subject: 'ig_chemistry', level: 'IGCSE', syllabus: '0620',
    paper: 'Paper 2', topic: 'Bonding', subtopic: 'Ionic bonding',
    syllabusRef: '4.2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'short-answer', marks: 3,
    skillsTested: ['bonding', 'explanation'],
    tags: ['ionic', 'electrons'], examFrequency: 'high',
    prompt: 'Describe what happens to the electrons when sodium reacts with chlorine to form sodium chloride.',
    options: null, correctAnswer: null,
    explanation: "Sodium loses one electron from its outer shell to form Na⁺. Chlorine gains this electron to form Cl⁻. The oppositely charged ions attract each other (ionic bond).",
    commonMistakes: ["Saying atoms 'share' electrons (that's covalent)", 'Forgetting to mention the electrostatic attraction'],
    teachingSteps: [
      'Na has 1 outer electron → loses it → Na⁺',
      'Cl has 7 outer electrons → gains 1 → Cl⁻',
      'Both now have full outer shells',
      'Na⁺ and Cl⁻ attract = ionic bond',
    ],
    aiMarkable: true, markScheme: ['Sodium loses electron / forms Na⁺ [1]', 'Chlorine gains electron / forms Cl⁻ [1]', 'Electrostatic attraction between ions [1]'],
  },
  {
    id: 'chem_003', subject: 'ig_chemistry', level: 'IGCSE', syllabus: '0620',
    paper: 'Paper 4', topic: 'Stoichiometry', subtopic: 'Moles',
    syllabusRef: '5.1', difficulty: 'hard', difficultyScore: 3,
    questionType: 'calculation', marks: 3,
    skillsTested: ['moles', 'calculation'],
    tags: ['moles', 'mass', 'Mr'], examFrequency: 'high',
    prompt: 'Calculate the number of moles in 5.3 g of Na₂CO₃. (Aᵣ: Na = 23, C = 12, O = 16)',
    options: null, correctAnswer: '0.050',
    explanation: 'Mr of Na₂CO₃ = 2(23) + 12 + 3(16) = 106. Moles = mass/Mr = 5.3/106 = 0.050 mol.',
    commonMistakes: ['Calculating Mr incorrectly', 'Dividing Mr by mass instead of mass by Mr'],
    teachingSteps: ['Find Mr: 2(23) + 12 + 3(16) = 106', 'Use n = m/Mr', 'n = 5.3/106', 'n = 0.050 mol'],
    aiMarkable: true, markScheme: ['Mr = 106 [1]', 'n = m/Mr used [1]', '0.050 mol [1]'],
  },
  {
    id: 'chem_004', subject: 'ig_chemistry', level: 'IGCSE', syllabus: '0620',
    paper: 'Paper 2', topic: 'Acids and Bases', subtopic: 'pH scale',
    syllabusRef: '8.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['recall'],
    tags: ['acids', 'pH', 'indicators'], examFrequency: 'high',
    prompt: 'What is the pH of a neutral solution?',
    options: ['0', '7', '14', '1'],
    correctAnswer: 1,
    explanation: 'Neutral pH is 7. Acids are below 7, alkalis are above 7.',
    commonMistakes: ['Thinking neutral is pH 0', 'Confusing pH scale direction'],
    teachingSteps: ['pH scale: 0–14', 'Acids: pH < 7', 'Neutral: pH = 7', 'Alkalis: pH > 7'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'chem_005', subject: 'ig_chemistry', level: 'IGCSE', syllabus: '0620',
    paper: 'Paper 4', topic: 'Electrolysis', subtopic: 'Products',
    syllabusRef: '6.2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['electrolysis'],
    tags: ['electrolysis', 'electrodes'], examFrequency: 'medium',
    prompt: 'During the electrolysis of concentrated sodium chloride solution, what gas is produced at the positive electrode (anode)?',
    options: ['Hydrogen', 'Oxygen', 'Chlorine', 'Sodium'],
    correctAnswer: 2,
    explanation: 'At the anode, chloride ions are discharged: 2Cl⁻ → Cl₂ + 2e⁻. Chlorine gas is produced.',
    commonMistakes: ['Confusing anode and cathode products', 'Thinking sodium is produced at an electrode'],
    teachingSteps: [
      'Anode = positive electrode',
      'Negative ions go to anode',
      'Cl⁻ ions are discharged',
      '2Cl⁻ → Cl₂ + 2e⁻',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'chem_006', subject: 'ig_chemistry', level: 'IGCSE', syllabus: '0620',
    paper: 'Paper 2', topic: 'Organic Chemistry', subtopic: 'Alkanes',
    syllabusRef: '11.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['organic chemistry'],
    tags: ['alkanes', 'hydrocarbons'], examFrequency: 'medium',
    prompt: 'What is the molecular formula of butane?',
    options: ['C₃H₈', 'C₄H₈', 'C₄H₁₀', 'C₅H₁₂'],
    correctAnswer: 2,
    explanation: 'Butane is an alkane (CₙH₂ₙ₊₂). For n = 4: C₄H₁₀.',
    commonMistakes: ['Using the alkene formula CₙH₂ₙ', 'Miscounting carbons'],
    teachingSteps: ['Alkane general formula: CₙH₂ₙ₊₂', "'But-' prefix = 4 carbons", 'H = 2(4) + 2 = 10', 'Molecular formula: C₄H₁₀'],
    aiMarkable: false, markScheme: null,
  },

  // ─── IGCSE ECONOMICS ───────────────────────────────────────────
  {
    id: 'econ_001', subject: 'ig_economics', level: 'IGCSE', syllabus: '0455',
    paper: 'Paper 1', topic: 'Basic Economic Problem', subtopic: 'Scarcity and choice',
    syllabusRef: '1.1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['concepts'],
    tags: ['scarcity', 'opportunity cost'], examFrequency: 'high',
    prompt: 'The basic economic problem arises because:',
    options: [
      'Governments do not plan properly',
      'Resources are unlimited but wants are limited',
      'Resources are limited but wants are unlimited',
      'People are greedy',
    ],
    correctAnswer: 2,
    explanation: 'The fundamental economic problem is that resources (factors of production) are scarce/limited while human wants are unlimited.',
    commonMistakes: ['Reversing limited/unlimited', 'Choosing a moral rather than economic answer'],
    teachingSteps: ['Resources = land, labour, capital, enterprise', 'These are finite/scarce', 'Human wants are infinite', 'This creates the need to choose = scarcity'],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'econ_002', subject: 'ig_economics', level: 'IGCSE', syllabus: '0455',
    paper: 'Paper 1', topic: 'Demand and Supply', subtopic: 'Demand shifts',
    syllabusRef: '2.2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['analysis', 'diagrams'],
    tags: ['demand', 'shift'], examFrequency: 'high',
    prompt: 'If the price of a substitute good increases, what happens to the demand curve for the original good?',
    options: ['Shifts left', 'Stays the same', 'Movement along the curve', 'Shifts right'],
    correctAnswer: 3,
    explanation: "If a substitute becomes more expensive, consumers switch to the original good, increasing its demand (rightward shift).",
    commonMistakes: ['Confusing shift with movement along curve', 'Confusing substitutes and complements'],
    teachingSteps: [
      'Substitute = alternative good',
      'Substitute price ↑ → people buy less of it',
      'They buy more of original good instead',
      'Demand curve shifts right',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'econ_003', subject: 'ig_economics', level: 'IGCSE', syllabus: '0455',
    paper: 'Paper 2', topic: 'Market Failure', subtopic: 'Externalities',
    syllabusRef: '3.3', difficulty: 'medium', difficultyScore: 2,
    questionType: 'short-answer', marks: 4,
    skillsTested: ['analysis', 'evaluation'],
    tags: ['externalities', 'market failure'], examFrequency: 'high',
    prompt: 'Explain what is meant by a negative externality and give one example.',
    options: null, correctAnswer: null,
    explanation: "A negative externality is a cost imposed on third parties who are not directly involved in the production or consumption of a good. Example: Factory pollution affecting local residents' health.",
    commonMistakes: ['Confusing private and external costs', 'Not identifying the third party'],
    teachingSteps: [
      'Externality = effect on third parties',
      'Negative = harmful/costly',
      'Third party = not buyer or seller',
      'Example: pollution, noise, passive smoking',
    ],
    aiMarkable: true, markScheme: ['Cost/harm to third parties [1]', 'Not involved in transaction [1]', 'Valid example [1]', 'Explanation of how third party is affected [1]'],
  },
  {
    id: 'econ_004', subject: 'ig_economics', level: 'IGCSE', syllabus: '0455',
    paper: 'Paper 1', topic: 'Price Elasticity', subtopic: 'PED',
    syllabusRef: '2.5', difficulty: 'hard', difficultyScore: 3,
    questionType: 'calculation', marks: 2,
    skillsTested: ['elasticity', 'calculation'],
    tags: ['PED', 'elasticity'], examFrequency: 'high',
    prompt: 'The price of a good rises from $10 to $12. Quantity demanded falls from 200 to 160. Calculate the price elasticity of demand (PED).',
    options: null, correctAnswer: '-1',
    explanation: '% change in Qd = (160-200)/200 × 100 = -20%. % change in price = (12-10)/10 × 100 = 20%. PED = -20/20 = -1.',
    commonMistakes: ['Forgetting the negative sign', 'Using final values instead of original for %change'],
    teachingSteps: [
      '% ΔQd = (160-200)/200 × 100 = -20%',
      '% ΔP = (12-10)/10 × 100 = +20%',
      'PED = %ΔQd / %ΔP',
      'PED = -20/20 = -1 (unit elastic)',
    ],
    aiMarkable: true, markScheme: ['Correct percentage changes [1]', 'PED = −1 [1]'],
  },
  {
    id: 'econ_005', subject: 'ig_economics', level: 'IGCSE', syllabus: '0455',
    paper: 'Paper 1', topic: 'Government Intervention', subtopic: 'Taxation',
    syllabusRef: '4.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['policy analysis'],
    tags: ['tax', 'government'], examFrequency: 'medium',
    prompt: 'An indirect tax on cigarettes would most likely:',
    options: ['Shift the demand curve left', 'Shift the supply curve left', 'Increase supply', 'Reduce price'],
    correctAnswer: 1,
    explanation: 'An indirect tax increases production costs, shifting the supply curve leftward (upward). This leads to higher price and lower quantity.',
    commonMistakes: ['Thinking tax shifts demand', 'Confusing direct and indirect tax effects'],
    teachingSteps: [
      'Indirect tax = tax on goods/services',
      'Added to production cost',
      'Supply curve shifts left/up',
      'Price rises, quantity falls',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'econ_006', subject: 'ig_economics', level: 'IGCSE', syllabus: '0455',
    paper: 'Paper 2', topic: 'International Trade', subtopic: 'Trade barriers',
    syllabusRef: '7.1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'essay', marks: 6,
    skillsTested: ['evaluation', 'extended writing'],
    tags: ['trade', 'protectionism'], examFrequency: 'medium',
    prompt: 'Discuss whether a government should use tariffs to protect domestic industries.',
    options: null, correctAnswer: null,
    explanation: 'Arguments for: protects infant industries, preserves jobs, prevents dumping, maintains strategic industries. Arguments against: higher prices for consumers, retaliation from trading partners, inefficiency, reduced choice.',
    commonMistakes: ['Only giving one side of the argument', 'Not providing a conclusion'],
    teachingSteps: [
      'Define tariff: tax on imports',
      'Arguments FOR protection (2-3 points)',
      'Arguments AGAINST protection (2-3 points)',
      'Conclude with balanced evaluation',
    ],
    aiMarkable: true, markScheme: ['Definition of tariff [1]', 'Arguments for (max 2 marks) [2]', 'Arguments against (max 2 marks) [2]', 'Balanced conclusion [1]'],
  },

  // ─── IGCSE ENGLISH LITERATURE ──────────────────────────────────
  {
    id: 'eng_001', subject: 'ig_english', level: 'IGCSE', syllabus: '0475',
    paper: 'Paper 1', topic: 'Poetry Analysis', subtopic: 'Poetic devices',
    syllabusRef: 'P1', difficulty: 'easy', difficultyScore: 1,
    questionType: 'mcq', marks: 1,
    skillsTested: ['literary devices'],
    tags: ['poetry', 'techniques'], examFrequency: 'high',
    prompt: "'The wind howled through the trees' is an example of:",
    options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'],
    correctAnswer: 2,
    explanation: "Personification gives human qualities to non-human things. 'Howled' is a human/animal action attributed to the wind.",
    commonMistakes: ['Confusing personification with metaphor', 'Not identifying the human quality'],
    teachingSteps: [
      'Personification = human qualities to non-human',
      "'Howled' = human/animal action",
      "Applied to 'wind' = non-human",
      'Therefore = personification',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'eng_002', subject: 'ig_english', level: 'IGCSE', syllabus: '0475',
    paper: 'Paper 1', topic: 'Prose Analysis', subtopic: 'Character analysis',
    syllabusRef: 'P1', difficulty: 'medium', difficultyScore: 2,
    questionType: 'essay', marks: 8,
    skillsTested: ['analysis', 'PEE paragraphs'],
    tags: ['character', 'analysis', 'essay'], examFrequency: 'high',
    prompt: "How does the writer use language to create a sense of tension in the following passage? 'The door creaked open. Shadows stretched across the floor like dark fingers reaching for her ankles. She held her breath.'",
    options: null, correctAnswer: null,
    explanation: "Tension is created through: auditory imagery ('creaked'), a simile comparing shadows to 'dark fingers' suggesting threat, personification of shadows 'reaching', short sentence 'She held her breath' creating urgency.",
    commonMistakes: ['Identifying techniques without explaining their effect', 'Retelling rather than analysing'],
    teachingSteps: [
      'Point: Identify a technique',
      'Evidence: Quote the exact words',
      'Explain: How does it create tension?',
      'Repeat for 2-3 techniques',
      'Link back to the question',
    ],
    aiMarkable: true, markScheme: ['Identifies relevant language features [2]', 'Selects appropriate quotations [2]', 'Explains effect on reader [2]', 'Focused analysis linked to tension [2]'],
  },
  {
    id: 'eng_003', subject: 'ig_english', level: 'IGCSE', syllabus: '0475',
    paper: 'Paper 2', topic: 'Drama', subtopic: 'Themes',
    syllabusRef: 'P2', difficulty: 'medium', difficultyScore: 2,
    questionType: 'mcq', marks: 1,
    skillsTested: ['themes'],
    tags: ['drama', 'themes'], examFrequency: 'medium',
    prompt: "In Shakespeare's plays, dramatic irony occurs when:",
    options: [
      'Two characters argue on stage',
      'The audience knows something a character does not',
      'A character speaks directly to the audience',
      'The plot has a surprising twist',
    ],
    correctAnswer: 1,
    explanation: 'Dramatic irony is when the audience has knowledge that characters on stage do not, creating tension or humour.',
    commonMistakes: ['Confusing dramatic irony with a soliloquy', 'Confusing it with a plot twist'],
    teachingSteps: [
      'Dramatic irony = audience knows more',
      'Character is unaware of key information',
      'Creates tension, humour, or pathos',
      'Different from verbal irony or situational irony',
    ],
    aiMarkable: false, markScheme: null,
  },
  {
    id: 'eng_004', subject: 'ig_english', level: 'IGCSE', syllabus: '0475',
    paper: 'Paper 1', topic: 'Prose Analysis', subtopic: "Writer's effects",
    syllabusRef: 'P1', difficulty: 'hard', difficultyScore: 3,
    questionType: 'short-answer', marks: 4,
    skillsTested: ['analysis', 'language'],
    tags: ['imagery', "writer's craft"], examFrequency: 'high',
    prompt: "Explain the effect of the metaphor: 'Time is a thief that steals our youth.'",
    options: null, correctAnswer: null,
    explanation: "The metaphor compares time to a thief, suggesting time takes away youth without permission, creating a sense of loss and inevitability. 'Steals' implies something valuable is being taken against our will.",
    commonMistakes: ['Just identifying it as a metaphor without analysing effect', "Not exploring connotations of 'thief' and 'steals'"],
    teachingSteps: [
      "Identify: metaphor comparing time to a thief",
      "Connotation of 'thief': criminal, takes without asking",
      "'Steals' implies loss is unwanted, inevitable",
      "Effect: reader feels time passing is a kind of loss",
    ],
    aiMarkable: true, markScheme: ['Identifies comparison (time/thief) [1]', "Explores connotation of 'thief' [1]", "'Steals' and loss [1]", "Comments on reader's response/effect [1]"],
  },
];

const QUESTION_MAP = Object.fromEntries(QUESTIONS.map(q => [q.id, q]));

function getTopicsForSubject(subjectId) {
  return [...new Set(QUESTIONS.filter(q => q.subject === subjectId).map(q => q.topic))];
}

function getPapersForSubject(subjectId) {
  return [...new Set(QUESTIONS.filter(q => q.subject === subjectId).map(q => q.paper))];
}

function getQuestionsForSubject(subjectId) {
  return QUESTIONS.filter(q => q.subject === subjectId);
}

function filterQuestions(subjectId, filters) {
  return QUESTIONS.filter(q => {
    if (subjectId && q.subject !== subjectId) return false;
    if (filters.paper && filters.paper !== 'all' && q.paper !== filters.paper) return false;
    if (filters.topic && filters.topic !== 'all' && q.topic !== filters.topic) return false;
    if (filters.difficulty && filters.difficulty !== 'all' && q.difficulty !== filters.difficulty) return false;
    if (filters.questionType && filters.questionType !== 'all' && q.questionType !== filters.questionType) return false;
    return true;
  });
}

function shuffleArray(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
